services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  api:
    build: .
    container_name: rag-api
    environment:
      - QDRANT_HOST=http://qdrant:6333
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    restart: unless-stopped

volumes:
  qdrant_storage:
